!!python/object:argparse.Namespace
batch_size: 32
device: cuda:0
epochs: 100
input_size: 7
latent_size: 2
lr: 0.0001
no_progress_bar: false
num_resamples: 10
steps_log_loss: 1000
steps_log_norm_params: 1000
